import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "도서 정보 등록",
  description: "Generated by create next app",
};

const BookTestCom = () => {
  return (
    <div>
      <h1>BookTestCom!!!!!!!!</h1>
    </div>
  );
};

export default BookTestCom;
